server:
   port: 8190
eureka:
    client:
       register-with-eureka: true
       fetch-registry: true
       serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}



spring:
   application:
      name: eureka-feign-order

   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cloud
      username: postgres
      password: 123456
   jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect
